// ------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전: 14.0.0.0
//  
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Merona.PacketGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class OutputCSharp : OutputCSharpBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 8 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 foreach(var entry in pgen.entries) { 
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 9 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.prefix));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t");
            
            #line 10 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 foreach(var packet in entry.packets) { 
            
            #line default
            #line hidden
            this.Write("\tpublic sealed class ");
            
            #line 11 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(packet.name));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t\t\r\n\t\t");
            
            #line 13 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
// C2S Fields 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 14 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 if(packet.c2sFields.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t[PacketId(");
            
            #line 15 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(id));
            
            #line default
            #line hidden
            this.Write(")]\r\n\t\t[StructLayout(LayoutKind.Sequential, Pack = 1)]\r\n\t\tpublic sealed class C2S " +
                    ": Merona.Packet {\r\n\t\t\t");
            
            #line 18 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 foreach(var field in packet.commonFields) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 19 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToCSharpField()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 20 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 21 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 foreach(var field in packet.c2sFields) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 22 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToCSharpField()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 23 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tpublic C2S() {\r\n\t\t\t\tthis.size = ");
            
            #line 26 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Marshal.SizeOf(packet.type)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\tthis.id = ");
            
            #line 27 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(id++));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t}\r\n\t\t");
            
            #line 30 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 32 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
// S2C Fields 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 33 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 if(packet.s2cFields.Count > 0) {  
            
            #line default
            #line hidden
            this.Write("\t\t[PacketId(");
            
            #line 34 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(id));
            
            #line default
            #line hidden
            this.Write(")]\r\n\t\t[StructLayout(LayoutKind.Sequential, Pack = 1)]\r\n\t\tpublic sealed class S2C " +
                    ": Merona.Packet {\r\n\t\t\t");
            
            #line 37 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 foreach(var field in packet.commonFields) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 38 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToCSharpField()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 39 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 40 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 foreach(var field in packet.s2cFields) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 41 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToCSharpField()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 42 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tpublic S2C() {\r\n\t\t\t\tthis.size = ");
            
            #line 45 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Marshal.SizeOf(packet.type)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\tthis.id = ");
            
            #line 46 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(id++));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t}\r\n\t\t");
            
            #line 49 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t}\r\n\t");
            
            #line 51 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 53 "C:\Users\hyun\Documents\GitHub\Merona.Pgen.cs\src\Merona.PacketGenerator\OutputCSharp.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class OutputCSharpBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
